### ISSUE TITLE
Clone RendererUtil.java

### ISSUE THREAD

**Issue by SahebChandok** [rilling/jmonkeyengineFall2024#56]
**Describe the clone**
This clone checks for OpenGL errors using glGetError and throws a RendererException with a descriptive error message if an error occurs.

**Location of the clones**
Provide the Filename/Line #
Starting at line 66 of C:\jmonkeyengineFall2024\jme3-android\src\main\java\com\jme3\renderer\android\RendererUtil.java
Starting at line 156 of C:\jmonkeyengineFall2024\jme3-android\src\main\java\com\jme3\renderer\android\RendererUtil.java

![image](https://github.com/user-attachments/assets/400f8792-8b1d-4e8c-95c7-19b1035b2af8)

**Clone Type**
Is it a type #1 or #2 clone
Type 1 

**Expected outcome**
Illustrate how the clone will be refactored

**Code before refactoring**
![image](https://github.com/user-attachments/assets/e8eb8985-36d8-4a21-a985-1111d9b47c8d)
![image](https://github.com/user-attachments/assets/01ce720e-285b-4af9-b8ff-2e5fe391c59d)

**Code after refactoring**
![image](https://github.com/user-attachments/assets/e30748b7-d1e0-49ab-b753-538a6e8f2a18)
![image](https://github.com/user-attachments/assets/e3195b6c-10cb-4567-af3b-2624065ac8e5)
![image](https://github.com/user-attachments/assets/4d1b0e95-ae02-4702-8777-574f7c87d9e9)

**Additional context**
A new function is created to solve this issue. This prevents code duplication.

**Comment by rajbhensdadiya** [comment]
Closing this issue in favor of this PR: https://github.com/rajbhensdadiya/jmonkeyengineFall2024/pull/10

**Comment by rajbhensdadiya** [comment]
Reopening this issue as it was linked to different PR

**Comment by rajbhensdadiya** [comment]
Closing this issue in favor of this PR: https://github.com/rajbhensdadiya/jmonkeyengineFall2024/pull/16
