### ISSUE TITLE
Refactor Duplicate File Descriptor Handling Logic in loadBuffer and loadStream Methods of NativeVorbisLoader.java

### ISSUE THREAD

**Issue by kawsarahmedbhuiyan** [rilling/jmonkeyengineFall2024#66]
**Describe the clone**
There is a 4-line code duplication in the `loadBuffer` method (line 100) and `loadStream` method (line 126) located in `NativeVorbisLoader.java`. The duplicated code handles file descriptor opening and resource cleanup for `AssetFileDescriptor` and `NativeVorbisFile` objects.

**Location of the clones**
- Starting at line 100 of `jme3-android\src\main\java\com\jme3\audio\plugins\NativeVorbisLoader.java`
- Starting at line 126 of `jme3-android\src\main\java\com\jme3\audio\plugins\NativeVorbisLoader.java`

![image](https://github.com/user-attachments/assets/173cbf9b-203f-45c0-ac3b-12183250e5f4)

**Clone Type**
Type 1 Clone

**Expected outcome**
Extract the duplicated code into two new private helper methods: `openFileDescriptor` and `closeResources`. The `openFileDescriptor` method will handle the opening of the file descriptor, while `closeResources` will handle the cleanup of resources. The `loadBuffer` and `loadStream` methods will call these helpers to reduce duplication and improve maintainability.

**Code before refactoring**
![image](https://github.com/user-attachments/assets/e07c1da7-df74-40b9-abe8-b3ad51014493)

**Code after refactoring**
![image](https://github.com/user-attachments/assets/982ac67d-d4d8-43f7-949c-e5a54353f9aa)

**Additional context**
This duplication creates unnecessary repetition, as the same logic for opening file descriptors and cleaning up resources appears in both the loadBuffer and loadStream methods, which makes the code harder to maintain and reduces its clarity.

**Comment by rajbhensdadiya** [comment]
Closing this issue in favor of this PR: https://github.com/rajbhensdadiya/jmonkeyengineFall2024/pull/15
